// Auto-generated by scripts/update-youtube.js
// Run `npm run update-youtube` to refresh with the latest full-length videos from the channel.
export const youtubeVideoIds = [
  "eEjRFFQDgCs",
  "V_IHJtwwsG0",
  "UaH29GF97no",
  "sBayrIVfGes",
  "Jp2eHm339Tk",
  "sB7pqGYSjgA",
];
