#!/usr/bin/env node
/**
 * Fetches the latest full-length videos from the Balanced Yoga with Kenz YouTube
 * channel by scraping the /videos tab (which excludes Shorts entirely).
 * Updates src/lib/youtube.ts with the 6 most recent full videos.
 *
 * Usage: npm run update-youtube
 */

const https = require("https");
const fs = require("fs");
const path = require("path");

// The /videos tab on a channel page only shows full-length videos (no Shorts)
const CHANNEL_VIDEOS_URL =
  "https://www.youtube.com/@BalancedYoga_withKenz/videos";
const OUTPUT_PATH = path.join(__dirname, "../src/lib/youtube.ts");
const VIDEO_COUNT = 6;

function fetchPage(url, redirectCount = 0) {
  if (redirectCount > 5) return Promise.reject(new Error("Too many redirects"));
  return new Promise((resolve, reject) => {
    https
      .get(
        url,
        {
          headers: {
            "User-Agent":
              "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
            "Accept-Language": "en-US,en;q=0.9",
            Accept:
              "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
          },
        },
        (res) => {
          if (
            res.statusCode >= 300 &&
            res.statusCode < 400 &&
            res.headers.location
          ) {
            res.resume();
            return fetchPage(res.headers.location, redirectCount + 1)
              .then(resolve)
              .catch(reject);
          }
          let data = "";
          res.on("data", (chunk) => (data += chunk));
          res.on("end", () => resolve(data));
        }
      )
      .on("error", reject);
  });
}

function extractVideoIds(html) {
  // YouTube embeds ytInitialData JSON in the page.
  // Full videos appear as "videoRenderer":{"videoId":"..."
  // Shorts appear as "reelItemRenderer" — by matching only videoRenderer we skip Shorts.
  const ids = [];
  const seen = new Set();
  const re = /"videoRenderer":\{"videoId":"([a-zA-Z0-9_-]{11})"/g;
  let match;
  while ((match = re.exec(html)) !== null) {
    if (!seen.has(match[1])) {
      seen.add(match[1]);
      ids.push(match[1]);
    }
  }
  return ids;
}

async function main() {
  console.log(`Fetching ${CHANNEL_VIDEOS_URL} ...`);
  const html = await fetchPage(CHANNEL_VIDEOS_URL);

  if (!html.includes("ytInitialData")) {
    throw new Error(
      "Could not find video data in page — YouTube may have blocked the request or changed its format."
    );
  }

  const ids = extractVideoIds(html);

  if (ids.length === 0) {
    throw new Error(
      "No full-length video IDs found. The page structure may have changed."
    );
  }

  // Filter to only embeddable videos using the oEmbed API.
  // YouTube returns 401 when a video has embedding disabled.
  console.log("Checking which videos allow embedding...");
  const embeddable = await Promise.all(
    ids.map((id) =>
      new Promise((resolve) => {
        https
          .get(
            `https://www.youtube.com/oembed?url=https://www.youtube.com/watch?v=${id}&format=json`,
            (res) => { res.resume(); resolve({ id, ok: res.statusCode === 200 }); }
          )
          .on("error", () => resolve({ id, ok: false }));
      })
    )
  );

  const embeddableIds = embeddable.filter((v) => v.ok).map((v) => v.id);
  const skipped = embeddable.filter((v) => !v.ok).map((v) => v.id);
  if (skipped.length > 0) {
    console.log(`Skipping ${skipped.length} video(s) with embedding disabled: ${skipped.join(", ")}`);
  }

  const selected = embeddableIds.slice(0, VIDEO_COUNT);

  if (selected.length === 0) {
    throw new Error("No embeddable videos found.");
  }
  if (selected.length < VIDEO_COUNT) {
    console.warn(`Warning: only ${selected.length} embeddable video(s) found (wanted ${VIDEO_COUNT}).`);
  }

  console.log(`Using ${selected.length} video(s):`);
  selected.forEach((id, i) =>
    console.log(`  ${i + 1}. https://www.youtube.com/watch?v=${id}`)
  );

  const fileContent = `// Auto-generated by scripts/update-youtube.js
// Run \`npm run update-youtube\` to refresh with the latest full-length videos from the channel.
export const youtubeVideoIds = [
${selected.map((id) => `  "${id}",`).join("\n")}
];
`;

  fs.writeFileSync(OUTPUT_PATH, fileContent, "utf8");
  console.log(`\nUpdated ${path.relative(process.cwd(), OUTPUT_PATH)}`);
}

main().catch((err) => {
  console.error("Error:", err.message);
  process.exit(1);
});
